version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=your-secret-key-here
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./backend/prisma:/app/prisma
      - backend_node_modules:/app/node_modules
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - NUXT_API_BASE_URL=http://backend:3000
    volumes:
      - frontend_node_modules:/app/node_modules
    networks:
      - app-network

volumes:
  backend_node_modules:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge
