version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=dev-secret-key-change-in-production
      - DATABASE_URL=file:./prisma/dev.db
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/api/health').then(r => process.exit(r.ok ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./backend/prisma:/app/prisma
    networks:
      - fullstack-network

  frontend:
    build: ./frontend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - NUXT_API_BASE_URL=http://backend:3000
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:3001
      - NITRO_PORT=3002
      - NITRO_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - backend
    networks:
      - fullstack-network

networks:
  fullstack-network:
    driver: bridge
